name: Called Workflow

on:
  workflow_call:
    inputs:
      ambiente:
        description: "Ambiente onde os testes serão executados"
        required: true
        type: string

jobs:
  run_web_test:
    name: Run Web Tests
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: |
          echo "Rodando testes web no ambiente de ${{ inputs.ambiente }}"